/**
 * Custom config plugin: fixSplashScreen.js
 *
 * expo-splash-screen unconditionally writes a `windowSplashScreenAnimatedIcon`
 * item into Theme.App.SplashScreen in styles.xml, even when no splash image is
 * configured. This causes Android build failures because the referenced
 * @drawable/splashscreen_logo file is never created.
 *
 * This plugin runs AFTER expo-splash-screen and removes that item so the build
 * succeeds cleanly. When a real splash image is configured (and the drawable
 * file therefore exists), the item is also supplied through the expo-splash-screen
 * plugin config array in app.json, making this a pure safety net.
 */

const { withAndroidStyles } = require('@expo/config-plugins');

/**
 * @param {import('@expo/config-plugins').ExpoConfig} config
 * @returns {import('@expo/config-plugins').ExpoConfig}
 */
const withFixSplashScreen = (config) => {
  return withAndroidStyles(config, (modConfig) => {
    const styles = modConfig.modResults;

    if (!styles.resources || !styles.resources.style) {
      return modConfig;
    }

    styles.resources.style = styles.resources.style.map((style) => {
      // Only touch the SplashScreen theme generated by expo-splash-screen
      if (style.$.name !== 'Theme.App.SplashScreen') {
        return style;
      }

      if (!style.item) {
        return style;
      }

      // Remove the windowSplashScreenAnimatedIcon item that references the
      // drawable which may not exist when no image is configured.
      style.item = style.item.filter(
        (item) => item.$.name !== 'windowSplashScreenAnimatedIcon'
      );

      return style;
    });

    return modConfig;
  });
};

module.exports = withFixSplashScreen;
